import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className="w-full h-full flex">
        <div className="w-48 h-full p-4 border border-black">SIDEBAR</div>
        <div className="flex-1 h-full p-4">{children}</div>
      </body>
    </html>
  );
}
